application:
  port: 0
  host: 0.0.0.0
  serve_dir: "./dist"
database:
  host: "127.0.0.1"
  port: 5432
  username: "username"
  password: "password"
  database_name: "gotcha"
  require_ssl: false
challenges: []
