[package]
name = "gotcha-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.7", features = ["macros"] }
axum-extra = "0.9"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time = { version = "0.3", features = ["serde", "formatting"] }
serde = { version = "1", features = ["derive"] }
serde-aux = "4"
secrecy = { version = "0.8", features = ["serde"] }
anyhow = "1"
thiserror = "1"
reqwest = { version = "0.12", features = ["json"] }
config = { version = "0.14", default-features = false, features = ["yaml"] }
jsonwebtoken = "9"
