[alias]
watch-server = [
    "watch",
    "-x",
    "run -q -p gotcha-server",
    "-i",
    "package-lock.json",
    "-i",
    "server/examples/client",
]
watch-client = [
    "watch",
    "-x",
    "run -q --example client",
    "-w",
    "server/examples",
]
sqlx-prepare = "sqlx prepare --workspace -- --all-targets --all-features"
