[alias]
watch-server = [
    "watch",
    "-x",
    "run -q -p gotcha-server",
    "-i",
    "package-lock.json",
    "-i",
    "server/examples/client",
]
watch-client = [
    "watch",
    "-x",
    "run -q --example client",
    "-w",
    "server/examples",
]
build-lambda = "lambda build --release --arm64 --features aws-lambda"
deploy-lambda = "lambda deploy gotcha-server --include dist/ --include config/"
sqlx-prepare = "sqlx prepare --workspace -- --all-targets --all-features"
