application:
  port: 0
  host: 0.0.0.0
  serve_dir: "./dist"
  auth_origin: "https://dev-gptk3ouno03gtjgs.us.auth0.com"
database:
  host: "127.0.0.1"
  port: 5432
  username: "username"
  password: "password"
  database_name: "gotcha"
  require_ssl: false
